workflows:
  ios-release-build:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Meetgo IOS
    environment:
      groups:
        - development
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.meetgo.vn
      vars:
        BUNDLE_ID: "app.meetgo.vn"
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "96D6FATL37"
        APP_STORE_CONNECT_ISSUER_ID: "c76b0f32-e565-4479-90c9-edc2487340a7"
        APP_STORE_APPLE_ID: 6467422791
        TEAM_ID: "M73GARWH95"
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          npm install && npx patch-package
          cd ios && pod install && cd ..
          
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles --project ios/*.xcodeproj
        
      - name: Update version numbers
        script: |
          cd ios
          
          # First, let's check current versions
          CURRENT_MARKETING_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" meetgo/Info.plist 2>/dev/null || echo "1.0")
          CURRENT_BUILD_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" meetgo/Info.plist 2>/dev/null || echo "1")
          
          echo "Current marketing version (CFBundleShortVersionString): $CURRENT_MARKETING_VERSION"
          echo "Current build version (CFBundleVersion): $CURRENT_BUILD_VERSION"
          
          # Set new marketing version (must be higher than 3.0.0)
          # You can change this to whatever version you want (e.g., 3.1.0, 4.0.0, etc.)
          NEW_MARKETING_VERSION="3.2.0"
          echo "Setting new marketing version to: $NEW_MARKETING_VERSION"
          
          # Update marketing version in Info.plist
          /usr/libexec/PlistBuddy -c "Set :CFBundleShortVersionString $NEW_MARKETING_VERSION" meetgo/Info.plist
          
          # Update marketing version in project.pbxproj
          sed -i '' "s/MARKETING_VERSION = [^;]*/MARKETING_VERSION = $NEW_MARKETING_VERSION/g" meetgo.xcodeproj/project.pbxproj
          
          # Get the latest build number from App Store Connect
          echo "Fetching latest build number from App Store Connect..."
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest build number from App Store: $LATEST_BUILD_NUMBER"
          
          # Validate that we got a valid number
          if ! [[ "$LATEST_BUILD_NUMBER" =~ ^[0-9]+$ ]]; then
            echo "Error: Could not fetch valid build number. Using fallback method."
            LATEST_BUILD_NUMBER=14  # Based on your previous error message
          fi
          
          # Calculate new build number (start fresh for new marketing version)
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          
          # Ensure minimum build number is higher than current App Store version
          if [ "$NEW_BUILD_NUMBER" -le 15 ]; then
            NEW_BUILD_NUMBER=16
          fi
          
          echo "New build number will be: $NEW_BUILD_NUMBER"
          
          # Update build number in Info.plist
          echo "Updating CFBundleVersion in Info.plist..."
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" meetgo/Info.plist
          
          # Update build number in project.pbxproj
          echo "Updating project.pbxproj with new build number..."
          sed -i '' "s/CURRENT_PROJECT_VERSION = [0-9]*/CURRENT_PROJECT_VERSION = $NEW_BUILD_NUMBER/g" meetgo.xcodeproj/project.pbxproj
          
          # Verify all updates
          UPDATED_MARKETING_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" meetgo/Info.plist)
          UPDATED_BUILD_VERSION=$(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" meetgo/Info.plist)
          
          echo "Successfully updated CFBundleShortVersionString to: $UPDATED_MARKETING_VERSION"
          echo "Successfully updated CFBundleVersion to: $UPDATED_BUILD_VERSION"
          
          # Verify project.pbxproj updates
          if grep -q "CURRENT_PROJECT_VERSION = $NEW_BUILD_NUMBER" meetgo.xcodeproj/project.pbxproj; then
            echo "Successfully updated CURRENT_PROJECT_VERSION in project.pbxproj"
          else
            echo "Warning: Could not verify CURRENT_PROJECT_VERSION update in project.pbxproj"
          fi
          
          if grep -q "MARKETING_VERSION = $NEW_MARKETING_VERSION" meetgo.xcodeproj/project.pbxproj; then
            echo "Successfully updated MARKETING_VERSION in project.pbxproj"
          else
            echo "Warning: Could not verify MARKETING_VERSION update in project.pbxproj"
          fi
          
       - name: Load Firebase configuration
        script: |
          #!/usr/bin/env sh
          set -e # exit on first failed command
          echo $IOS_FIREBASE_SECRET > $CM_BUILD_DIR/ios/GoogleService-Info.plist
          
      - name: Verify build configuration
        script: |
          cd ios
          echo "=== Final Build Configuration Verification ==="
          echo "Marketing Version (CFBundleShortVersionString): $(/usr/libexec/PlistBuddy -c "Print :CFBundleShortVersionString" meetgo/Info.plist)"
          echo "Build Version (CFBundleVersion): $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" meetgo/Info.plist)"
          echo "Bundle Identifier: $(/usr/libexec/PlistBuddy -c "Print :CFBundleIdentifier" meetgo/Info.plist)"
          
          # Check project.pbxproj for consistency
          echo ""
          echo "Project Configuration:"
          echo "MARKETING_VERSION in project.pbxproj:"
          grep "MARKETING_VERSION" meetgo.xcodeproj/project.pbxproj | head -3
          echo "CURRENT_PROJECT_VERSION in project.pbxproj:"
          grep "CURRENT_PROJECT_VERSION" meetgo.xcodeproj/project.pbxproj | head -3
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "ios/meetgo.xcworkspace" \
            --scheme "meetgo"
            
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
      
    publishing:
      email:
        recipients:
          - thenguyenfiner@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - app-beta
          - meetgo-beta-02
        submit_to_app_store: false