workflows:
  ios-release-build:
    name: iOS Release Build
    max_build_duration: 120
    instance_type: mac_mini_m2
    integrations:
      app_store_connect: Meetgo IOS
    environment:
      groups:
        - development
      ios_signing:
        distribution_type: app_store
        bundle_identifier: app.meetgo.vn
      vars:
        BUNDLE_ID: "app.meetgo.vn"
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "96D6FATL37"
        APP_STORE_CONNECT_ISSUER_ID: "c76b0f32-e565-4479-90c9-edc2487340a7"
        APP_STORE_APPLE_ID: 6467422791
        TEAM_ID: "M73GARWH95"
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install CocoaPods dependencies
        script: |
          npm install && npx patch-package
          cd ios && pod install && cd ..
          
      - name: Set up provisioning profiles settings on Xcode project
        script: xcode-project use-profiles --project ios/*.xcodeproj
        
      - name: Increment build number
        script: |
          cd ios
          # Get the latest build number from App Store Connect
          LATEST_BUILD_NUMBER=$(app-store-connect get-latest-app-store-build-number "$APP_STORE_APPLE_ID")
          echo "Latest build number from App Store: $LATEST_BUILD_NUMBER"
          
          # Calculate new build number
          NEW_BUILD_NUMBER=$((LATEST_BUILD_NUMBER + 1))
          echo "New build number will be: $NEW_BUILD_NUMBER"
          
          # Update Info.plist with new build number
          /usr/libexec/PlistBuddy -c "Set :CFBundleVersion $NEW_BUILD_NUMBER" meetgo/Info.plist
          
          # Verify the update
          echo "Updated CFBundleVersion to: $(/usr/libexec/PlistBuddy -c "Print :CFBundleVersion" meetgo/Info.plist)"
          
      - name: Add GoogleService-Info.plist
        script: |
          # Add GoogleService-Info.plist to fix Firebase configuration
          # Make sure you have uploaded GoogleService-Info.plist as a secure file in Codemagic
          echo "Adding GoogleService-Info.plist to ios/"
          
          # If you have the file as a secure file in Codemagic:
          # cp $CM_BUILD_DIR/GoogleService-Info.plist ios/meetgo/GoogleService-Info.plist
          
          # Or if it's in your repository but gitignored, you might need to create it:
          # For now, let's check if it exists
          if [ ! -f "ios/GoogleService-Info.plist" ]; then
            echo "WARNING: GoogleService-Info.plist not found. Firebase features may not work."
            echo "Please add GoogleService-Info.plist as a secure file in Codemagic settings."
          else
            echo "GoogleService-Info.plist found successfully"
          fi
          
      - name: Build ipa for distribution
        script: |
          xcode-project build-ipa \
            --workspace "ios/meetgo.xcworkspace" \
            --scheme "meetgo"
    artifacts:
      - build/ios/ipa/*.ipa
      - /tmp/xcodebuild_logs/*.log
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.app
      - $HOME/Library/Developer/Xcode/DerivedData/**/Build/**/*.dSYM
    publishing:
      email:
        recipients:
          - thenguyenfiner@gmail.com
        notify:
          success: true
          failure: false
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - app-beta
          - meetgo-beta-02
        submit_to_app_store: false