workflows:
  ios-release-build:
    name: iOS Release Build
    instance_type: mac_mini_m1
    max_build_duration: 120
    integrations:
      app_store_connect: Meetgo IOS
    environment:
      groups:
        - development
      vars:
        XCODE_WORKSPACE: "ios/meetgo.xcworkspace"
        XCODE_SCHEME: "meetgo"
        IPHONEOS_DEPLOYMENT_TARGET: "15.5"
        APP_STORE_CONNECT_KEY_IDENTIFIER: "96D6FATL37"
        APP_STORE_CONNECT_ISSUER_ID: "c76b0f32-e565-4479-90c9-edc2487340a7"
        BUNDLE_ID: "app.meetgo.vn"
        TEAM_ID: "M73GARWH95"
      xcode: 16.2
      cocoapods: default
    scripts:
      - name: Install dependencies
        script: |
          npm install && npx patch-package
          cd ios && pod install && cd ..
          
      - name: Set up code signing
        script: |
          # Initialize keychain for Codemagic
          keychain initialize
          
          # Fetch and install signing files from App Store Connect
          # Use IOS_APP_STORE since you're using App Store Connect for provisioning
          app-store-connect fetch-signing-files "$BUNDLE_ID" \
            --type IOS_APP_STORE \
            --create
            
          # Apply code signing settings to Xcode project
          xcode-project use-profiles
          
          # Verify setup
          echo "Available certificates:"
          security find-identity -v -p codesigning
          
          echo "Available provisioning profiles:"
          find ~/Library/MobileDevice/Provisioning\ Profiles/ -name "*.mobileprovision" -exec basename {} \; 2>/dev/null || echo "No profiles found"
          
      - name: Update Pod targets and Swift optimization
        script: |
          cd ios
          # Update deployment targets to 15.5 
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9]*\.[0-9]*/IPHONEOS_DEPLOYMENT_TARGET = 15.5/g' Pods/Target\ Support\ Files/*/*.xcconfig || true
          
          # Fix Swift optimization level for debugging
          find Pods/Target\ Support\ Files -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -Owholemodule;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          find Pods/Target\ Support\ Files -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -O;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          
          # Update main project settings
          find . -name "*.xcconfig" -exec sed -i '' 's/SWIFT_OPTIMIZATION_LEVEL = -O[a-z]*;/SWIFT_OPTIMIZATION_LEVEL = -Onone;/g' {} \;
          cd ..
          
      - name: Build iOS app
        script: |
          mkdir -p build
          set -x
          
          echo "Starting build process with team ID: $TEAM_ID"
          
          # Clean build
          xcodebuild clean \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release
          
          # Build archive for App Store
          xcodebuild \
          -workspace "$XCODE_WORKSPACE" \
          -scheme "$XCODE_SCHEME" \
          -configuration Release \
          -sdk iphoneos \
          -archivePath build/meetgo.xcarchive \
          IPHONEOS_DEPLOYMENT_TARGET=15.5 \
          DEVELOPMENT_TEAM="$TEAM_ID" \
          CODE_SIGN_STYLE=Manual \
          SWIFT_OPTIMIZATION_LEVEL="-Onone" \
          archive | tee xcodebuild.log
          
          # Check if archive was created
          if [ -d "build/meetgo.xcarchive" ]; then
            echo "Archive created successfully"
            
            # Create exportOptions.plist for App Store distribution
            cat > ios/exportOptions.plist << EOL
          <?xml version="1.0" encoding="UTF-8"?>
          <!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
          <plist version="1.0">
          <dict>
              <key>method</key>
              <string>app-store</string>
              <key>teamID</key>
              <string>$TEAM_ID</string>
              <key>signingStyle</key>
              <string>automatic</string>
              <key>stripSwiftSymbols</key>
              <true/>
              <key>uploadBitcode</key>
              <false/>
              <key>uploadSymbols</key>
              <true/>
              <key>compileBitcode</key>
              <false/>
          </dict>
          </plist>
          EOL
            
            echo "Generated exportOptions.plist:"
            cat ios/exportOptions.plist
            
            # Export the archive
            xcodebuild \
            -exportArchive \
            -archivePath build/meetgo.xcarchive \
            -exportOptionsPlist ios/exportOptions.plist \
            -exportPath build/ios
            
            if [ $? -eq 0 ]; then
              echo "Export successful"
              ls -la build/ios/
            else
              echo "Export failed"
              exit 1
            fi
          else
            echo "Archive creation failed"
            tail -n 100 xcodebuild.log
            exit 1
          fi
    artifacts:
      - build/ios/*.ipa
      - xcodebuild.log
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
        beta_groups:
          - Internal Testers
      email:
        recipients:
          - your.email@example.com
        notify:
          success: true
          failure: true