const Images = {
  intro: {
    intro1: require('../assets/background/intro1.png'),
    intro2: require('../assets/background/intro2.png'),
    intro3: require('../assets/background/intro3.png'),
  },
  global: {
    logo: require('../assets/IconApp.png'),
    logoPadding: require('../assets/iconAppPadding.png'),
    guideBg: require('../assets/background/guildBg.jpeg'),
    guideBg2: require('../assets/background/guildBg2.jpeg'),
    guideBg3: require('../assets/background/guildBg3.jpeg'),
    mapBg: require('../assets/background/map.png'),
    emptyImg: require('../assets/emptyImg.jpeg'),
    emptyNft: require('../assets/emptyNft.png'),
    requestLocation: require('../assets/requestLocation.png'),
    requestLocation2: require('../assets/requestLocation2.png'),
    requestCamera: require('../assets/requestCamera.png'),
  },
  nft: {
    borderMap: require('../assets/background/borderMap.png'),
    borderAddress: require('../assets/background/borderAddress.png'),
    borderLat: require('../assets/background/borderLat.png'),
    borderLong: require('../assets/background/borderLong.png'),
    borderOwner: require('../assets/background/borderOwner.png'),
  },
  icon: {
    direct: require('../assets/direct.png'),
    locationBuy: require('../assets/icon/locationBuy.png'),
    locationShop: require('../assets/icon/locationShop.png'),
    locationPending: require('../assets/icon/locationPending.png'),
    locationGift: require('../assets/icon/locationGift.png'),
    logoApple: require('../assets/icon/48px/logoApple.png'),
    logoGoogle: require('../assets/icon/48px/logoGoogle.png'),
    home: {
      qr: require('../assets/icon/40px/QR.png'),
      connect: require('../assets/icon/40px/Connect.png'),
      history: require('../assets/icon/40px/History.png'),
      invite: require('../assets/icon/40px/Invite.png'),
    },
    bottomTab: {
      home: require('../assets/icon/30px/iconHome.png'),
      account: require('../assets/icon/30px/iconAccount.png'),
      scan: require('../assets/icon/30px/iconScan.png'),
      location: require('../assets/icon/30px/iconLocation.png'),
    },
    logoPoint: require('../assets/icon/logoPoint.png'),
    pin: require('../assets/icon/pin.png'),
    birth: require('../assets/icon/birth.png'),
    threeDots: require('../assets/icon/3dots.png'),
    account: {
      iconHistoryEarn: require('../assets/icon/24px/iconHistoryEarn.png'),
      iconHistoryMeet: require('../assets/icon/24px/iconHistoryMeet.png'),
      iconInviteFriends: require('../assets/icon/24px/iconInviteFriends.png'),
      iconManageAcc: require('../assets/icon/24px/iconManageAcc.png'),
      iconPolicy: require('../assets/icon/24px/iconPolicy.png'),
      iconReferral: require('../assets/icon/24px/iconReferral.png'),
      iconSearch: require('../assets/icon/24px/iconSearch.png'),
      iconSecurity: require('../assets/icon/24px/iconSecurity.png'),
      iconVerify: require('../assets/icon/24px/iconVerify.png'),
      iconPen: require('../assets/icon/24px/iconPen.png'),
      iconLanguage: require('../assets/icon/24px/iconLanguage.png'),
    },
    userScan: {
      iconPhone: require('../assets/icon/24px/iconPhone.png'),
      iconSex: require('../assets/icon/24px/iconSex.png'),
    },
  },
  animation: {
    location: require('../assets/animation/location.json'),
    location2: require('../assets/animation/location2.json'),
    permissionLocation: require('../assets/animation/permissionLocation.json'),
    introLocation: require('../assets/animation/introLocation.json'),
    emptyLocation: require('../assets/animation/emptyLocation.json'),
    qrscan: require('../assets/animation/qrcode.json'),
    meetTogether: require('../assets/animation/meetTogether.json'),
    success: require('../assets/animation/success.json'),
    waitingTime: require('../assets/animation/waitingTime.json'),
    ringing: require('../assets/animation/ringing.json'),
    earnSuccess: require('../assets/animation/earnSuccess.json'),
  },
  guide: {
    step1: require('../assets/guide/step1.jpg'),
    step2: require('../assets/guide/step2.jpg'),
    step3_1: require('../assets/guide/step3.1.jpg'),
    step3_2: require('../assets/guide/step3.2.jpg'),
    step4: require('../assets/guide/step4.jpg'),
    step5: require('../assets/guide/step5.jpg'),
    step6: require('../assets/guide/step6.jpg'),
  },
  earn: {
    background: require('../assets/background/earning.png'),
    earnExit: require('../assets/background/earnExit.png'),
  },
  meet: {
    waitingMeet: require('../assets/background/waitingMeet.png'),
    meetTogether: require('../assets/background/meetTogether.png'),
  },
};
export default Images;
